const express = require("express");
const router = express.Router();
const infoapi = [
  {
    id: 1,
    image: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
    name: "Affenpinscher",
    temperament: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving",
    weight: { imperial: "6 - 13", metric: "3 - 6" },
    height: { imperial: "9 - 11.5", metric: "23 - 29" },
    life_span: "10 - 12 years",
  },
  {
    id: 2,
    image: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
    name: "Afghan Hound",
    temperament: "Aloof, Clownish, Dignified, Independent, Happy",
    weight: { imperial: "50 - 60", metric: "23 - 27" },
    height: { imperial: "25 - 27", metric: "64 - 69" },
    life_span: "10 - 13 years",
  },
  {
    id: 3,
    image: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
    name: "African Hunting Dog",
    temperament: "Wild, Hardworking, Dutiful",
    weight: { imperial: "44 - 66", metric: "20 - 30" },
    height: { imperial: "30", metric: "76" },
    life_span: "11 years",
  },
  {
    id: 4,
    image: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
    name: "Airedale Terrier",
    temperament:
      "Outgoing, Friendly, Alert, Confident, Intelligent, Courageous",
    weight: { imperial: "40 - 65", metric: "18 - 29" },
    height: { imperial: "21 - 23", metric: "53 - 58" },
    life_span: "10 - 13 years",
  },
  {
    id: 5,
    image: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
    name: "Akbash Dog",
    temperament: "Loyal, Independent, Intelligent, Brave",
    weight: { imperial: "90 - 120", metric: "41 - 54" },
    height: { imperial: "28 - 34", metric: "71 - 86" },
    life_span: "10 - 12 years",
  },
  {
    id: 6,
    image: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
    name: "Akita",
    temperament:
      "Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous",
    weight: { imperial: "65 - 115", metric: "29 - 52" },
    height: { imperial: "24 - 28", metric: "61 - 71" },
    life_span: "10 - 14 years",
  },
  {
    id: 7,
    image: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
    name: "Alapaha Blue Blood Bulldog",
    temperament: "Loving, Protective, Trainable, Dutiful, Responsible",
    weight: { imperial: "55 - 90", metric: "25 - 41" },
    height: { imperial: "18 - 24", metric: "46 - 61" },
    life_span: "12 - 13 years",
  },
  {
    id: 8,
    image: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
    name: "Alaskan Husky",
    temperament: "Friendly, Energetic, Loyal, Gentle, Confident",
    weight: { imperial: "38 - 50", metric: "17 - 23" },
    height: { imperial: "23 - 26", metric: "58 - 66" },
    life_span: "10 - 13 years",
  },
  {
    id: 9,
    image: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
    name: "Alaskan Malamute",
    temperament: "Friendly, Affectionate, Devoted, Loyal, Dignified, Playful",
    weight: { imperial: "65 - 100", metric: "29 - 45" },
    height: { imperial: "23 - 25", metric: "58 - 64" },
    life_span: "12 - 15 years",
  },
  {
    id: 10,
    image: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
    name: "American Bulldog",
    temperament:
      "Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant",
    weight: { imperial: "60 - 120", metric: "27 - 54" },
    height: { imperial: "22 - 27", metric: "56 - 69" },
    life_span: "10 - 12 years",
  },
  {
    id: 11,
    image: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
    name: "American Bully",
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
    weight: { imperial: "30 - 150", metric: "14 - 68" },
    height: { imperial: "14 - 17", metric: "36 - 43" },
    life_span: "8 – 15 years",
  },
  {
    id: 12,
    image: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
    name: "American Eskimo Dog",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
    weight: { imperial: "20 - 40", metric: "9 - 18" },
    height: { imperial: "15 - 19", metric: "38 - 48" },
    life_span: "12 - 15 years",
  },
  {
    id: 13,
    image: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
    name: "American Eskimo Dog (Miniature)",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
    weight: { imperial: "7 - 10", metric: "3 - 5" },
    height: { imperial: "9 - 12", metric: "23 - 30" },
    life_span: "13 – 15 years",
  },
  {
    id: 14,
    image: "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
    name: "American Foxhound",
    temperament:
      "Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving",
    weight: { imperial: "65 - 75", metric: "29 - 34" },
    height: { imperial: "21 - 28", metric: "53 - 71" },
    life_span: "8 - 15 years",
  },
  {
    id: 15,
    image: "https://cdn2.thedogapi.com/images/HkC31gcNm.png",
    name: "American Pit Bull Terrier",
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
    weight: { imperial: "30 - 60", metric: "14 - 27" },
    height: { imperial: "17 - 21", metric: "43 - 53" },
    life_span: "10 - 15 years",
  },
  {
    id: 16,
    image: "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
    name: "American Staffordshire Terrier",
    temperament: "Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous",
    weight: { imperial: "50 - 60", metric: "23 - 27" },
    height: { imperial: "17 - 19", metric: "43 - 48" },
    life_span: "12 - 15 years",
  },
  {
    id: 17,
    image: "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
    name: "American Water Spaniel",
    temperament:
      "Friendly, Energetic, Obedient, Intelligent, Protective, Trainable",
    weight: { imperial: "25 - 45", metric: "11 - 20" },
    height: { imperial: "15 - 18", metric: "38 - 46" },
    life_span: "10 - 12 years",
  },
  {
    id: 18,
    image: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
    name: "Anatolian Shepherd Dog",
    temperament: "Steady, Bold, Independent, Confident, Intelligent, Proud",
    weight: { imperial: "80 - 150", metric: "36 - 68" },
    height: { imperial: "27 - 29", metric: "69 - 74" },
    life_span: "11 - 13 years",
  },
  {
    id: 19,
    image: "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
    name: "Appenzeller Sennenhund",
    temperament: "Reliable, Fearless, Energetic, Lively, Self-assured",
    weight: { imperial: "48 - 55", metric: "22 - 25" },
    height: { imperial: "20 - 22", metric: "51 - 56" },
    life_span: "12 – 14 years",
  },
  {
    id: 21,
    image: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
    name: "Australian Cattle Dog",
    temperament: "Cautious, Energetic, Loyal, Obedient, Protective, Brave",
    weight: { imperial: "44 - 62", metric: "20 - 28" },
    height: { imperial: "17 - 20", metric: "43 - 51" },
    life_span: "12 - 14 years",
  },
  {
    id: 22,
    image: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
    name: "Australian Kelpie",
    temperament: "Friendly, Energetic, Alert, Loyal, Intelligent, Eager",
    weight: { imperial: "31 - 46", metric: "14 - 21" },
    height: { imperial: "17 - 20", metric: "43 - 51" },
    life_span: "10 - 13 years",
  },
  {
    id: 23,
    image: "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
    name: "Australian Shepherd",
    temperament: "Good-natured, Affectionate, Intelligent, Active, Protective",
    weight: { imperial: "35 - 65", metric: "16 - 29" },
    height: { imperial: "18 - 23", metric: "46 - 58" },
    life_span: "12 - 16 years",
  },
  {
    id: 24,
    image: "https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg",
    name: "Australian Terrier",
    temperament:
      "Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous",
    weight: { imperial: "14 - 16", metric: "6 - 7" },
    height: { imperial: "10 - 11", metric: "25 - 28" },
    life_span: "15 years",
  },
  {
    id: 25,
    image: "https://cdn2.thedogapi.com/images/SkvZgx94m.jpg",
    name: "Azawakh",
    temperament: "Aloof, Affectionate, Attentive, Rugged, Fierce, Refined",
    weight: { imperial: "33 - 55", metric: "15 - 25" },
    height: { imperial: "23 - 29", metric: "58 - 74" },
    life_span: "10 - 13 years",
  },
  {
    id: 26,
    image: "https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg",
    name: "Barbet",
    temperament: "Obedient, Companionable, Intelligent, Joyful",
    weight: { imperial: "40 - 65", metric: "18 - 29" },
    height: { imperial: "20 - 26", metric: "51 - 66" },
    life_span: "13 – 15 years",
  },
  {
    id: 28,
    image: "https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg",
    name: "Basenji",
    temperament:
      "Affectionate, Energetic, Alert, Curious, Playful, Intelligent",
    weight: { imperial: "22 - 24", metric: "10 - 11" },
    height: { imperial: "16 - 17", metric: "41 - 43" },
    life_span: "10 - 12 years",
  },
  {
    id: 29,
    image: "https://cdn2.thedogapi.com/images/BkMQll94X.jpg",
    name: "Basset Bleu de Gascogne",
    temperament: "Affectionate, Lively, Agile, Curious, Happy, Active",
    weight: { imperial: "35 - 40", metric: "16 - 18" },
    height: { imperial: "13 - 15", metric: "33 - 38" },
    life_span: "10 - 14 years",
  },
  {
    id: 30,
    image: "https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg",
    name: "Basset Hound",
    temperament:
      "Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle",
    weight: { imperial: "50 - 65", metric: "23 - 29" },
    height: { imperial: "14", metric: "36" },
    life_span: "12 - 15 years",
  },
  {
    id: 31,
    image: "https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg",
    name: "Beagle",
    temperament:
      "Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent",
    weight: { imperial: "20 - 35", metric: "9 - 16" },
    height: { imperial: "13 - 15", metric: "33 - 38" },
    life_span: "13 - 16 years",
  },
  {
    id: 32,
    image: "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
    name: "Bearded Collie",
    temperament: "Self-confidence, Hardy, Lively, Alert, Intelligent, Active",
    weight: { imperial: "45 - 55", metric: "20 - 25" },
    height: { imperial: "20 - 22", metric: "51 - 56" },
    life_span: "12 - 14 years",
  },
  {
    id: 33,
    image: "https://cdn2.thedogapi.com/images/HJQ8ge5V7.jpg",
    name: "Beauceron",
    temperament: "Fearless, Friendly, Intelligent, Protective, Calm",
    weight: { imperial: "80 - 110", metric: "36 - 50" },
    height: { imperial: "24 - 27.5", metric: "61 - 70" },
    life_span: "10 - 12 years",
  },
  {
    id: 34,
    image: "https://cdn2.thedogapi.com/images/ByK8gx947.jpg",
    name: "Bedlington Terrier",
    temperament: "Affectionate, Spirited, Intelligent, Good-tempered",
    weight: { imperial: "17 - 23", metric: "8 - 10" },
    height: { imperial: "15 - 16", metric: "38 - 41" },
    life_span: "14 - 16 years",
  },
  {
    id: 36,
    image: "https://cdn2.thedogapi.com/images/r1f_ll5VX.jpg",
    name: "Belgian Malinois",
    temperament:
      "Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective",
    weight: { imperial: "40 - 80", metric: "18 - 36" },
    height: { imperial: "22 - 26", metric: "56 - 66" },
    life_span: "12 - 14 years",
  },
  {
    id: 38,
    image: "https://cdn2.thedogapi.com/images/B1KdxlcNX.jpg",
    name: "Belgian Tervuren",
    temperament: "Energetic, Alert, Loyal, Intelligent, Attentive, Protective",
    weight: { imperial: "40 - 65", metric: "18 - 29" },
    height: { imperial: "22 - 26", metric: "56 - 66" },
    life_span: "10 - 12 years",
  },
  {
    id: 41,
    image: "https://cdn2.thedogapi.com/images/S1fFlx5Em.jpg",
    name: "Bernese Mountain Dog",
    temperament: "Affectionate, Loyal, Intelligent, Faithful",
    weight: { imperial: "65 - 120", metric: "29 - 54" },
    height: { imperial: "23 - 27.5", metric: "58 - 70" },
    life_span: "7 - 10 years",
  },
  {
    id: 42,
    image: "https://cdn2.thedogapi.com/images/HkuYlxqEQ.jpg",
    name: "Bichon Frise",
    temperament: "Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive",
    weight: { imperial: "10 - 18", metric: "5 - 8" },
    height: { imperial: "9.5 - 11.5", metric: "24 - 29" },
    life_span: "15 years",
  },
  {
    id: 43,
    image: "https://cdn2.thedogapi.com/images/HJAFgxcNQ.jpg",
    name: "Black and Tan Coonhound",
    temperament:
      "Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable",
    weight: { imperial: "65 - 100", metric: "29 - 45" },
    height: { imperial: "23 - 27", metric: "58 - 69" },
    life_span: "10 - 12 years",
  },
  {
    id: 45,
    image: "https://cdn2.thedogapi.com/images/Skdcgx9VX.jpg",
    name: "Bloodhound",
    temperament: "Stubborn, Affectionate, Gentle, Even Tempered",
    weight: { imperial: "80 - 110", metric: "36 - 50" },
    height: { imperial: "23 - 27", metric: "58 - 69" },
    life_span: "8 - 10 years",
  },
  {
    id: 47,
    image: "https://cdn2.thedogapi.com/images/rJxieg9VQ.jpg",
    name: "Bluetick Coonhound",
    temperament: "Friendly, Intelligent, Active",
    weight: { imperial: "45 - 80", metric: "20 - 36" },
    height: { imperial: "21 - 27", metric: "53 - 69" },
    life_span: "12 - 14 years",
  },
  {
    id: 48,
    image: "https://cdn2.thedogapi.com/images/HyOjge5Vm.jpg",
    name: "Boerboel",
    temperament: "Obedient, Confident, Intelligent, Dominant, Territorial",
    weight: { imperial: "110 - 200", metric: "50 - 91" },
    height: { imperial: "22 - 27", metric: "56 - 69" },
    life_span: "10 - 12 years",
  },
  {
    id: 50,
    image: "https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg",
    name: "Border Collie",
    temperament: "Tenacious, Keen, Energetic, Responsive, Alert, Intelligent",
    weight: { imperial: "30 - 45", metric: "14 - 20" },
    height: { imperial: "18 - 22", metric: "46 - 56" },
    life_span: "12 - 16 years",
  },
  {
    id: 51,
    image: "https://cdn2.thedogapi.com/images/HJOpge9Em.jpg",
    name: "Border Terrier",
    temperament:
      "Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered",
    weight: { imperial: "11.5 - 15.5", metric: "5 - 7" },
    height: { imperial: "11 - 16", metric: "28 - 41" },
    life_span: "12 - 14 years",
  },
  {
    id: 53,
    image: "https://cdn2.thedogapi.com/images/rkZRggqVX.jpg",
    name: "Boston Terrier",
    temperament: "Friendly, Lively, Intelligent",
    weight: { imperial: "10 - 25", metric: "5 - 11" },
    height: { imperial: "16 - 17", metric: "41 - 43" },
    life_span: "11 - 13 years",
  },
  {
    id: 54,
    image: "https://cdn2.thedogapi.com/images/Byd0xl5VX.jpg",
    name: "Bouvier des Flandres",
    temperament: "Protective, Loyal, Gentle, Intelligent, Familial, Rational",
    weight: { imperial: "70 - 110", metric: "32 - 50" },
    height: { imperial: "23.5 - 27.5", metric: "60 - 70" },
    life_span: "10 - 15 years",
  },
  {
    id: 55,
    image: "https://cdn2.thedogapi.com/images/ry1kWe5VQ.jpg",
    name: "Boxer",
    temperament:
      "Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm",
    weight: { imperial: "50 - 70", metric: "23 - 32" },
    height: { imperial: "21.5 - 25", metric: "55 - 64" },
    life_span: "8 - 10 years",
  },
  {
    id: 56,
    image: "https://cdn2.thedogapi.com/images/ryHJZlcNX.jpg",
    name: "Boykin Spaniel",
    temperament:
      "Friendly, Energetic, Companionable, Intelligent, Eager, Trainable",
    weight: { imperial: "25 - 40", metric: "11 - 18" },
    height: { imperial: "14 - 18", metric: "36 - 46" },
    life_span: "10 - 14 years",
  },
  {
    id: 57,
    image: "https://cdn2.thedogapi.com/images/S13yZg5VQ.jpg",
    name: "Bracco Italiano",
    temperament:
      "Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable",
    weight: { imperial: "55 - 88", metric: "25 - 40" },
    height: { imperial: "21.5 - 26.5", metric: "55 - 67" },
    life_span: "10 - 12 years",
  },
  {
    id: 58,
    image: "https://cdn2.thedogapi.com/images/rkVlblcEQ.jpg",
    name: "Briard",
    temperament: "Fearless, Loyal, Obedient, Intelligent, Faithful, Protective",
    weight: { imperial: "70 - 90", metric: "32 - 41" },
    height: { imperial: "22 - 27", metric: "56 - 69" },
    life_span: "10 - 12 years",
  },
  {
    id: 59,
    image: "https://cdn2.thedogapi.com/images/HJWZZxc4X.jpg",
    name: "Brittany",
    temperament: "Agile, Adaptable, Quick, Intelligent, Attentive, Happy",
    weight: { imperial: "30 - 45", metric: "14 - 20" },
    height: { imperial: "17.5 - 20.5", metric: "44 - 52" },
    life_span: "12 - 14 years",
  },
  {
    id: 61,
    image: "https://cdn2.thedogapi.com/images/VSraIEQGd.jpg",
    name: "Bull Terrier",
    temperament: "Trainable, Protective, Sweet-Tempered, Keen, Active",
    weight: { imperial: "50 - 70", metric: "23 - 32" },
    height: { imperial: "21 - 22", metric: "53 - 56" },
    life_span: "10 - 12 years",
  },
  {
    id: 62,
    image: "https://cdn2.thedogapi.com/images/BkKZWlcVX.jpg",
    name: "Bull Terrier (Miniature)",
    temperament:
      "Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial",
    weight: { imperial: "25 - 33", metric: "11 - 15" },
    height: { imperial: "10 - 14", metric: "25 - 36" },
    life_span: "11 – 14 years",
  },
  {
    id: 64,
    image: "https://cdn2.thedogapi.com/images/r1ifZl5E7.jpg",
    name: "Bullmastiff",
    temperament:
      "Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous",
    weight: { imperial: "100 - 130", metric: "45 - 59" },
    height: { imperial: "24 - 27", metric: "61 - 69" },
    life_span: "8 - 12 years",
  },
  {
    id: 65,
    image: "https://cdn2.thedogapi.com/images/Sk7Qbg9E7.jpg",
    name: "Cairn Terrier",
    temperament: "Hardy, Fearless, Assertive, Gay, Intelligent, Active",
    weight: { imperial: "13 - 14", metric: "6 - 6" },
    height: { imperial: "9 - 10", metric: "23 - 25" },
    life_span: "14 - 15 years",
  },
  {
    id: 67,
    image: "https://cdn2.thedogapi.com/images/r15m-lc4m.jpg",
    name: "Cane Corso",
    temperament: "Trainable, Reserved, Stable, Quiet, Even Tempered, Calm",
    weight: { imperial: "88 - 120", metric: "40 - 54" },
    height: { imperial: "23.5 - 27.5", metric: "60 - 70" },
    life_span: "10 - 11 years",
  },
  {
    id: 68,
    image: "https://cdn2.thedogapi.com/images/SyXN-e9NX.jpg",
    name: "Cardigan Welsh Corgi",
    temperament:
      "Affectionate, Devoted, Alert, Companionable, Intelligent, Active",
    weight: { imperial: "25 - 38", metric: "11 - 17" },
    height: { imperial: "10.5 - 12.5", metric: "27 - 32" },
    life_span: "12 - 14 years",
  },
  {
    id: 69,
    image: "https://cdn2.thedogapi.com/images/BJcNbec4X.jpg",
    name: "Catahoula Leopard Dog",
    temperament:
      "Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving",
    weight: { imperial: "50 - 95", metric: "23 - 43" },
    height: { imperial: "20 - 26", metric: "51 - 66" },
    life_span: "10 - 12 years",
  },
  {
    id: 70,
    image: "https://cdn2.thedogapi.com/images/r1rrWe5Em.jpg",
    name: "Caucasian Shepherd (Ovcharka)",
    temperament: "Alert, Quick, Dominant, Powerful, Calm, Strong",
    weight: { imperial: "80 - 100", metric: "36 - 45" },
    height: { imperial: "24 - 33.5", metric: "61 - 85" },
    life_span: "10 - 12 years",
  },
  {
    id: 71,
    image: "https://cdn2.thedogapi.com/images/HJRBbe94Q.jpg",
    name: "Cavalier King Charles Spaniel",
    temperament:
      "Fearless, Affectionate, Sociable, Patient, Playful, Adaptable",
    weight: { imperial: "13 - 18", metric: "6 - 8" },
    height: { imperial: "12 - 13", metric: "30 - 33" },
    life_span: "10 - 14 years",
  },
  {
    id: 76,
    image: "https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg",
    name: "Chesapeake Bay Retriever",
    temperament:
      "Affectionate, Intelligent, Quiet, Dominant, Happy, Protective",
    weight: { imperial: "55 - 80", metric: "25 - 36" },
    height: { imperial: "21 - 26", metric: "53 - 66" },
    life_span: "10 - 13 years",
  },
  {
    id: 78,
    image: "https://cdn2.thedogapi.com/images/B1pDZx9Nm.jpg",
    name: "Chinese Crested",
    temperament: "Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy",
    weight: { imperial: "10 - 13", metric: "5 - 6" },
    height: { imperial: "11 - 13", metric: "28 - 33" },
    life_span: "10 - 14 years",
  },
  {
    id: 79,
    image: "https://cdn2.thedogapi.com/images/B1ruWl94Q.jpg",
    name: "Chinese Shar-Pei",
    temperament:
      "Suspicious, Affectionate, Devoted, Reserved, Independent, Loving",
    weight: { imperial: "45 - 60", metric: "20 - 27" },
    height: { imperial: "18 - 20", metric: "46 - 51" },
    life_span: "10 years",
  },
  {
    id: 80,
    image: "https://cdn2.thedogapi.com/images/Sypubg54Q.jpg",
    name: "Chinook",
    temperament: "Friendly, Alert, Dignified, Intelligent, Calm",
    weight: { imperial: "50 - 90", metric: "23 - 41" },
    height: { imperial: "22 - 26", metric: "56 - 66" },
    life_span: "12 - 15 years",
  },
  {
    id: 81,
    image: "https://cdn2.thedogapi.com/images/ry8KWgqEQ.jpg",
    name: "Chow Chow",
    temperament: "Aloof, Loyal, Independent, Quiet",
    weight: { imperial: "40 - 70", metric: "18 - 32" },
    height: { imperial: "17 - 20", metric: "43 - 51" },
    life_span: "12 - 15 years",
  },
  {
    id: 84,
    image: "https://cdn2.thedogapi.com/images/rkeqWgq4Q.jpg",
    name: "Clumber Spaniel",
    temperament: "Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted",
    weight: { imperial: "55 - 85", metric: "25 - 39" },
    height: { imperial: "17 - 20", metric: "43 - 51" },
    life_span: "10 - 12 years",
  },
  {
    id: 86,
    image: "https://cdn2.thedogapi.com/images/1lFmrzECl.jpg",
    name: "Cocker Spaniel",
    temperament: "Trainable, Friendly, Affectionate, Playful, Quiet, Faithful",
    weight: { imperial: "20 - 30", metric: "9 - 14" },
    height: { imperial: "14 - 15", metric: "36 - 38" },
    life_span: "12 - 15 years",
  },
  {
    id: 87,
    image: "https://cdn2.thedogapi.com/images/HkRcZe547.jpg",
    name: "Cocker Spaniel (American)",
    temperament: "Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry",
    weight: { imperial: "20 - 30", metric: "9 - 14" },
    height: { imperial: "14 - 15", metric: "36 - 38" },
    life_span: "12 - 15 years",
  },
  {
    id: 89,
    image: "https://cdn2.thedogapi.com/images/SyviZlqNm.jpg",
    name: "Coton de Tulear",
    temperament: "Affectionate, Lively, Playful, Intelligent, Trainable, Vocal",
    weight: { imperial: "9 - 15", metric: "4 - 7" },
    height: { imperial: "9 - 11", metric: "23 - 28" },
    life_span: "13 - 16 years",
  },
  {
    id: 92,
    image: "https://cdn2.thedogapi.com/images/SkJ3blcN7.jpg",
    name: "Dalmatian",
    temperament:
      "Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active",
    weight: { imperial: "50 - 55", metric: "23 - 25" },
    height: { imperial: "19 - 23", metric: "48 - 58" },
    life_span: "10 - 13 years",
  },
  {
    id: 94,
    image: "https://cdn2.thedogapi.com/images/HyL3bl94Q.jpg",
    name: "Doberman Pinscher",
    temperament:
      "Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent",
    weight: { imperial: "66 - 88", metric: "30 - 40" },
    height: { imperial: "24 - 28", metric: "61 - 71" },
    life_span: "10 years",
  },
  {
    id: 95,
    image: "https://cdn2.thedogapi.com/images/S1nhWx94Q.jpg",
    name: "Dogo Argentino",
    temperament:
      "Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective",
    weight: { imperial: "80 - 100", metric: "36 - 45" },
    height: { imperial: "23.5 - 27", metric: "60 - 69" },
    life_span: "10 - 12 years",
  },
  {
    id: 98,
    image: "https://cdn2.thedogapi.com/images/BkE6Wg5E7.jpg",
    name: "Dutch Shepherd",
    temperament: "Reliable, Affectionate, Alert, Loyal, Obedient, Trainable",
    weight: { imperial: "50 - 70", metric: "23 - 32" },
    height: { imperial: "22 - 24.5", metric: "56 - 62" },
    life_span: "15 years",
  },
  {
    id: 101,
    image: "https://cdn2.thedogapi.com/images/By4A-eqVX.jpg",
    name: "English Setter",
    temperament:
      "Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented",
    weight: { imperial: "45 - 80", metric: "20 - 36" },
    height: { imperial: "24 - 25", metric: "61 - 64" },
    life_span: "12 years",
  },
  {
    id: 102,
    image: "https://cdn2.thedogapi.com/images/H1QyMe5EQ.jpg",
    name: "English Shepherd",
    temperament: "Kind, Energetic, Independent, Adaptable, Intelligent, Bossy",
    weight: { imperial: "44 - 66", metric: "20 - 30" },
    height: { imperial: "18 - 23", metric: "46 - 58" },
    life_span: "10 - 13 years",
  },
  {
    id: 103,
    image: "https://cdn2.thedogapi.com/images/Hk0Jfe5VQ.jpg",
    name: "English Springer Spaniel",
    temperament:
      "Affectionate, Cheerful, Alert, Intelligent, Attentive, Active",
    weight: { imperial: "35 - 50", metric: "16 - 23" },
    height: { imperial: "19 - 20", metric: "48 - 51" },
    life_span: "12 - 14 years",
  },
  {
    id: 104,
    image: "https://cdn2.thedogapi.com/images/SkIgzxqNQ.jpg",
    name: "English Toy Spaniel",
    temperament: "Affectionate, Reserved, Playful, Gentle, Happy, Loving",
    weight: { imperial: "8 - 14", metric: "4 - 6" },
    height: { imperial: "10", metric: "25" },
    life_span: "10 - 12 years",
  },
  {
    id: 105,
    image: "https://cdn2.thedogapi.com/images/SJ6eMxqEQ.jpg",
    name: "English Toy Terrier",
    temperament:
      "Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable",
    weight: { imperial: "6 - 8", metric: "3 - 4" },
    height: { imperial: "10 - 12", metric: "25 - 30" },
    life_span: "12 - 13 years",
  },
  {
    id: 107,
    image: "https://cdn2.thedogapi.com/images/S1VWGx9Nm.jpg",
    name: "Eurasier",
    temperament: "Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm",
    weight: { imperial: "40 - 70", metric: "18 - 32" },
    height: { imperial: "20.5 - 23.5", metric: "52 - 60" },
    life_span: "12 - 14 years",
  },
  {
    id: 108,
    image: "https://cdn2.thedogapi.com/images/SkJfGecE7.jpg",
    name: "Field Spaniel",
    temperament: "Docile, Cautious, Sociable, Sensitive, Adaptable, Familial",
    weight: { imperial: "35 - 50", metric: "16 - 23" },
    height: { imperial: "17 - 18", metric: "43 - 46" },
    life_span: "11 - 15 years",
  },
  {
    id: 110,
    image: "https://cdn2.thedogapi.com/images/S1KMGg5Vm.jpg",
    name: "Finnish Lapphund",
    temperament: "Friendly, Keen, Faithful, Calm, Courageous",
    weight: { imperial: "33 - 53", metric: "15 - 24" },
    height: { imperial: "16 - 21", metric: "41 - 53" },
    life_span: "12 - 15 years",
  },
  {
    id: 111,
    image: "https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg",
    name: "Finnish Spitz",
    temperament: "Playful, Loyal, Independent, Intelligent, Happy, Vocal",
    weight: { imperial: "23 - 28", metric: "10 - 13" },
    height: { imperial: "15.5 - 20", metric: "39 - 51" },
    life_span: "12 - 15 years",
  },
  {
    id: 113,
    image: "https://cdn2.thedogapi.com/images/HyWNfxc47.jpg",
    name: "French Bulldog",
    temperament:
      "Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright",
    weight: { imperial: "28", metric: "13" },
    height: { imperial: "11 - 12", metric: "28 - 30" },
    life_span: "9 - 11 years",
  },
  {
    id: 114,
    image: "https://cdn2.thedogapi.com/images/B1u4zgqE7.jpg",
    name: "German Pinscher",
    temperament:
      "Spirited, Lively, Intelligent, Loving, Even Tempered, Familial",
    weight: { imperial: "25 - 45", metric: "11 - 20" },
    height: { imperial: "17 - 20", metric: "43 - 51" },
    life_span: "12 - 14 years",
  },
  {
    id: 115,
    image: "https://cdn2.thedogapi.com/images/SJyBfg5NX.jpg",
    name: "German Shepherd Dog",
    temperament:
      "Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous",
    weight: { imperial: "50 - 90", metric: "23 - 41" },
    height: { imperial: "22 - 26", metric: "56 - 66" },
    life_span: "10 - 13 years",
  },
  {
    id: 116,
    image: "https://cdn2.thedogapi.com/images/SJqBMg5Nm.jpg",
    name: "German Shorthaired Pointer",
    temperament:
      "Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable",
    weight: { imperial: "45 - 70", metric: "20 - 32" },
    height: { imperial: "21 - 25", metric: "53 - 64" },
    life_span: "12 - 14 years",
  },
  {
    id: 119,
    image: "https://cdn2.thedogapi.com/images/H1NIzlcV7.jpg",
    name: "Giant Schnauzer",
    temperament: "Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful",
    weight: { imperial: "65 - 90", metric: "29 - 41" },
    height: { imperial: "23.5 - 27.5", metric: "60 - 70" },
    life_span: "10 - 12 years",
  },
  {
    id: 120,
    image: "https://cdn2.thedogapi.com/images/H1oLMe94m.jpg",
    name: "Glen of Imaal Terrier",
    temperament: "Spirited, Agile, Loyal, Gentle, Active, Courageous",
    weight: { imperial: "32 - 40", metric: "15 - 18" },
    height: { imperial: "12.5 - 14", metric: "32 - 36" },
    life_span: "12 - 15 years",
  },
  {
    id: 121,
    image: "https://cdn2.thedogapi.com/images/HJ7Pzg5EQ.jpg",
    name: "Golden Retriever",
    temperament:
      "Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident",
    weight: { imperial: "55 - 75", metric: "25 - 34" },
    height: { imperial: "21.5 - 24", metric: "55 - 61" },
    life_span: "10 - 12 years",
  },
  {
    id: 123,
    image: "https://cdn2.thedogapi.com/images/SJ5vzx5NX.jpg",
    name: "Gordon Setter",
    temperament: "Fearless, Alert, Loyal, Confident, Gay, Eager",
    weight: { imperial: "45 - 80", metric: "20 - 36" },
    height: { imperial: "23 - 27", metric: "58 - 69" },
    life_span: "10 - 12 years",
  },
  {
    id: 124,
    image: "https://cdn2.thedogapi.com/images/B1Edfl9NX.jpg",
    name: "Great Dane",
    temperament: "Friendly, Devoted, Reserved, Gentle, Confident, Loving",
    weight: { imperial: "110 - 190", metric: "50 - 86" },
    height: { imperial: "28 - 32", metric: "71 - 81" },
    life_span: "7 - 10 years",
  },
  {
    id: 125,
    image: "https://cdn2.thedogapi.com/images/B12uzg9V7.png",
    name: "Great Pyrenees",
    temperament:
      "Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident",
    weight: { imperial: "85 - 115", metric: "39 - 52" },
    height: { imperial: "25 - 32", metric: "64 - 81" },
    life_span: "10 - 12 years",
  },
  {
    id: 127,
    image: "https://cdn2.thedogapi.com/images/ryNYMx94X.jpg",
    name: "Greyhound",
    temperament:
      "Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered",
    weight: { imperial: "50 - 70", metric: "23 - 32" },
    height: { imperial: "27 - 30", metric: "69 - 76" },
    life_span: "10 - 13 years",
  },
  {
    id: 128,
    image: "https://cdn2.thedogapi.com/images/ryoYGec4Q.jpg",
    name: "Griffon Bruxellois",
    temperament:
      "Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful",
    weight: { imperial: "12", metric: "5" },
    height: { imperial: "9 - 11", metric: "23 - 28" },
    life_span: "10 – 15 years",
  },
  {
    id: 129,
    image: "https://cdn2.thedogapi.com/images/B1IcfgqE7.jpg",
    name: "Harrier",
    temperament:
      "Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active",
    weight: { imperial: "40 - 60", metric: "18 - 27" },
    height: { imperial: "18 - 22", metric: "46 - 56" },
    life_span: "12 - 15 years",
  },
  {
    id: 130,
    image: "https://cdn2.thedogapi.com/images/rkXiGl9V7.jpg",
    name: "Havanese",
    temperament:
      "Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent",
    weight: { imperial: "7 - 13", metric: "3 - 6" },
    height: { imperial: "8.5 - 11.5", metric: "22 - 29" },
    life_span: "14 - 15 years",
  },
  {
    id: 134,
    image: "https://cdn2.thedogapi.com/images/S1osGeqVm.jpg",
    name: "Irish Setter",
    temperament:
      "Affectionate, Energetic, Lively, Independent, Playful, Companionable",
    weight: { imperial: "35 - 70", metric: "16 - 32" },
    height: { imperial: "24 - 27", metric: "61 - 69" },
    life_span: "10 - 11 years",
  },
  {
    id: 135,
    image: "https://cdn2.thedogapi.com/images/By-hGecVX.jpg",
    name: "Irish Terrier",
    temperament:
      "Respectful, Lively, Intelligent, Dominant, Protective, Trainable",
    weight: { imperial: "25 - 27", metric: "11 - 12" },
    height: { imperial: "18", metric: "46" },
    life_span: "12 - 16 years",
  },
  {
    id: 137,
    image: "https://cdn2.thedogapi.com/images/Hyd2zgcEX.jpg",
    name: "Irish Wolfhound",
    temperament:
      "Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous",
    weight: { imperial: "105 - 180", metric: "48 - 82" },
    height: { imperial: "30 - 35", metric: "76 - 89" },
    life_span: "6 - 8 years",
  },
  {
    id: 138,
    image: "https://cdn2.thedogapi.com/images/SJAnzg9NX.jpg",
    name: "Italian Greyhound",
    temperament:
      "Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent",
    weight: { imperial: "7 - 15", metric: "3 - 7" },
    height: { imperial: "13 - 15", metric: "33 - 38" },
    life_span: "12 - 15 years",
  },
  {
    id: 140,
    image: "https://cdn2.thedogapi.com/images/r1H6feqEm.jpg",
    name: "Japanese Chin",
    temperament: "Alert, Loyal, Independent, Intelligent, Loving, Cat-like",
    weight: { imperial: "4 - 9", metric: "2 - 4" },
    height: { imperial: "8 - 11", metric: "20 - 28" },
    life_span: "12 - 14 years",
  },
  {
    id: 141,
    image: "https://cdn2.thedogapi.com/images/HksaMxqNX.jpg",
    name: "Japanese Spitz",
    temperament:
      "Affectionate, Obedient, Playful, Companionable, Intelligent, Proud",
    weight: { imperial: "15 - 19", metric: "7 - 9" },
    height: { imperial: "12 - 15", metric: "30 - 38" },
    life_span: "10 – 16 years",
  },
  {
    id: 142,
    image: "https://cdn2.thedogapi.com/images/S1GAGg9Vm.jpg",
    name: "Keeshond",
    temperament: "Agile, Obedient, Playful, Quick, Sturdy, Bright",
    weight: { imperial: "35 - 45", metric: "16 - 20" },
    height: { imperial: "17 - 18", metric: "43 - 46" },
    life_span: "12 - 15 years",
  },
  {
    id: 144,
    image: "https://cdn2.thedogapi.com/images/Bko0fl547.jpg",
    name: "Komondor",
    temperament: "Steady, Fearless, Affectionate, Independent, Gentle, Calm",
    weight: { imperial: "80 - 100", metric: "36 - 45" },
    height: { imperial: "25.5 - 27.5", metric: "65 - 70" },
    life_span: "10 - 12 years",
  },
  {
    id: 145,
    image: "https://cdn2.thedogapi.com/images/kOMy84GQE.jpg",
    name: "Kooikerhondje",
    temperament: "Benevolent, Agile, Alert, Intelligent, Active, Territorial",
    weight: { imperial: "20 - 30", metric: "9 - 14" },
    height: { imperial: "14 - 16", metric: "36 - 41" },
    life_span: "12 - 15 years",
  },
  {
    id: 147,
    image: "https://cdn2.thedogapi.com/images/BykZ7ecVX.jpg",
    name: "Kuvasz",
    temperament:
      "Clownish, Loyal, Patient, Independent, Intelligent, Protective",
    weight: { imperial: "70 - 115", metric: "32 - 52" },
    height: { imperial: "26 - 30", metric: "66 - 76" },
    life_span: "8 - 10 years",
  },
  {
    id: 149,
    image: "https://cdn2.thedogapi.com/images/B1uW7l5VX.jpg",
    name: "Labrador Retriever",
    temperament:
      "Kind, Outgoing, Agile, Gentle, Intelligent, Trusting, Even Tempered",
    weight: { imperial: "55 - 80", metric: "25 - 36" },
    height: { imperial: "21.5 - 24.5", metric: "55 - 62" },
    life_span: "10 - 13 years",
  },
  {
    id: 151,
    image: "https://cdn2.thedogapi.com/images/ryzzmgqE7.jpg",
    name: "Lagotto Romagnolo",
    temperament: "Keen, Loyal, Companionable, Loving, Active, Trainable",
    weight: { imperial: "24 - 35", metric: "11 - 16" },
    height: { imperial: "16 - 19", metric: "41 - 48" },
    life_span: "14 - 16 years",
  },
  {
    id: 153,
    image: "https://cdn2.thedogapi.com/images/S1RGml5Em.jpg",
    name: "Lancashire Heeler",
    temperament: "Clever, Friendly, Alert, Intelligent",
    weight: { imperial: "6 - 13", metric: "3 - 6" },
    height: { imperial: "10 - 12", metric: "25 - 30" },
    life_span: "12 – 15 years",
  },
  {
    id: 155,
    image: "https://cdn2.thedogapi.com/images/ByrmQlqVm.jpg",
    name: "Leonberger",
    temperament: "Obedient, Fearless, Loyal, Companionable, Adaptable, Loving",
    weight: { imperial: "120 - 170", metric: "54 - 77" },
    height: { imperial: "25.5 - 31.5", metric: "65 - 80" },
    life_span: "6 - 8 years",
  },
  {
    id: 156,
    image: "https://cdn2.thedogapi.com/images/SJp7Qe5EX.jpg",
    name: "Lhasa Apso",
    temperament:
      "Steady, Fearless, Friendly, Devoted, Assertive, Spirited, Energetic, Lively, Alert, Obedient, Playful, Intelligent",
    weight: { imperial: "12 - 18", metric: "5 - 8" },
    height: { imperial: "10 - 11", metric: "25 - 28" },
    life_span: "12 - 15 years",
  },
  {
    id: 161,
    image: "https://cdn2.thedogapi.com/images/B1SV7gqN7.jpg",
    name: "Maltese",
    temperament:
      "Playful, Docile, Fearless, Affectionate, Sweet-Tempered, Lively, Responsive, Easygoing, Gentle, Intelligent, Active",
    weight: { imperial: "4 - 7", metric: "2 - 3" },
    height: { imperial: "8 - 10", metric: "20 - 25" },
    life_span: "15 - 18 years",
  },
  {
    id: 165,
    image: "https://cdn2.thedogapi.com/images/BkHHQgcN7.jpg",
    name: "Miniature American Shepherd",
    temperament: "Energetic, Loyal, Intelligent, Trainable",
    weight: { imperial: "20 - 40", metric: "9 - 18" },
    height: { imperial: "13 - 18", metric: "33 - 46" },
    life_span: "12 - 15 years",
  },
  {
    id: 167,
    image: "https://cdn2.thedogapi.com/images/Hy3H7g94X.jpg",
    name: "Miniature Pinscher",
    temperament: "Clever, Outgoing, Friendly, Energetic, Responsive, Playful",
    weight: { imperial: "8 - 11", metric: "4 - 5" },
    height: { imperial: "10 - 12.5", metric: "25 - 32" },
    life_span: "15 years",
  },
  {
    id: 168,
    image: "https://cdn2.thedogapi.com/images/SJIUQl9NX.jpg",
    name: "Miniature Schnauzer",
    temperament: "Fearless, Friendly, Spirited, Alert, Obedient, Intelligent",
    weight: { imperial: "11 - 20", metric: "5 - 9" },
    height: { imperial: "12 - 14", metric: "30 - 36" },
    life_span: "12 - 14 years",
  },
  {
    id: 171,
    image: "https://cdn2.thedogapi.com/images/Sk4DXl54m.jpg",
    name: "Newfoundland",
    temperament: "Sweet-Tempered, Gentle, Trainable",
    weight: { imperial: "100 - 150", metric: "45 - 68" },
    height: { imperial: "26 - 28", metric: "66 - 71" },
    life_span: "8 - 10 years",
  },
  {
    id: 172,
    image: "https://cdn2.thedogapi.com/images/B1ADQg94X.jpg",
    name: "Norfolk Terrier",
    temperament:
      "Self-confidence, Fearless, Spirited, Companionable, Happy, Lovable",
    weight: { imperial: "11 - 12", metric: "5 - 5" },
    height: { imperial: "9 - 10", metric: "23 - 25" },
    life_span: "12 - 15 years",
  },
  {
    id: 176,
    image: "https://cdn2.thedogapi.com/images/BkgKXlqE7.jpg",
    name: "Norwich Terrier",
    temperament: "Hardy, Affectionate, Energetic, Sensitive, Intelligent",
    weight: { imperial: "11 - 12", metric: "5 - 5" },
    height: { imperial: "10", metric: "25" },
    life_span: "12 - 15 years",
  },
  {
    id: 177,
    image: "https://cdn2.thedogapi.com/images/SyYtQe5V7.jpg",
    name: "Nova Scotia Duck Tolling Retriever",
    temperament: "Outgoing, Alert, Patient, Intelligent, Loving",
    weight: { imperial: "35 - 50", metric: "16 - 23" },
    height: { imperial: "17 - 21", metric: "43 - 53" },
    life_span: "12 - 14 years",
  },
  {
    id: 178,
    image: "https://cdn2.thedogapi.com/images/HkZ57lq4m.jpg",
    name: "Old English Sheepdog",
    temperament: "Sociable, Bubbly, Playful, Adaptable, Intelligent, Loving",
    weight: { imperial: "60 - 100", metric: "27 - 45" },
    height: { imperial: "21", metric: "53" },
    life_span: "10 - 12 years",
  },
  {
    id: 181,
    image: "https://cdn2.thedogapi.com/images/SkJj7e547.jpg",
    name: "Papillon",
    temperament: "Hardy, Friendly, Energetic, Alert, Intelligent, Happy",
    weight: { imperial: "3 - 12", metric: "1 - 5" },
    height: { imperial: "8 - 11", metric: "20 - 28" },
    life_span: "13 - 17 years",
  },
  {
    id: 183,
    image: "https://cdn2.thedogapi.com/images/ByIiml9Nm.jpg",
    name: "Pekingese",
    temperament:
      "Opinionated, Good-natured, Stubborn, Affectionate, Aggressive, Intelligent",
    weight: { imperial: "14", metric: "6" },
    height: { imperial: "6 - 9", metric: "15 - 23" },
    life_span: "14 - 18 years",
  },
  {
    id: 184,
    image: "https://cdn2.thedogapi.com/images/rJ6iQeqEm.jpg",
    name: "Pembroke Welsh Corgi",
    temperament: "Tenacious, Outgoing, Friendly, Bold, Playful, Protective",
    weight: { imperial: "25 - 30", metric: "11 - 14" },
    height: { imperial: "10 - 12", metric: "25 - 30" },
    life_span: "12 - 14 years",
  },
  {
    id: 185,
    image: "https://cdn2.thedogapi.com/images/S1V3Qeq4X.jpg",
    name: "Perro de Presa Canario",
    temperament: "Strong Willed, Suspicious, Gentle, Dominant, Calm",
    weight: { imperial: "88 - 110", metric: "40 - 50" },
    height: { imperial: "22 - 25.5", metric: "56 - 65" },
    life_span: "10 - 12 years",
  },
  {
    id: 188,
    image: "https://cdn2.thedogapi.com/images/Byz6mgqEQ.jpg",
    name: "Pharaoh Hound",
    temperament:
      "Affectionate, Sociable, Playful, Intelligent, Active, Trainable",
    weight: { imperial: "40 - 60", metric: "18 - 27" },
    height: { imperial: "21 - 25", metric: "53 - 64" },
    life_span: "12 - 14 years",
  },
  {
    id: 189,
    image: "https://cdn2.thedogapi.com/images/B1i67l5VQ.jpg",
    name: "Plott",
    temperament: "Bold, Alert, Loyal, Intelligent",
    weight: { imperial: "40 - 60", metric: "18 - 27" },
    height: { imperial: "20 - 25", metric: "51 - 64" },
    life_span: "12 - 14 years",
  },
  {
    id: 193,
    image: "https://cdn2.thedogapi.com/images/HJd0XecNX.jpg",
    name: "Pomeranian",
    temperament:
      "Extroverted, Friendly, Sociable, Playful, Intelligent, Active",
    weight: { imperial: "3 - 7", metric: "1 - 3" },
    height: { imperial: "8 - 12", metric: "20 - 30" },
    life_span: "15 years",
  },
  {
    id: 196,
    image: "https://cdn2.thedogapi.com/images/Hkxk4ecVX.jpg",
    name: "Poodle (Miniature)",
    temperament: "no info",
    weight: { imperial: "15 - 17", metric: "7 - 8" },
    height: { imperial: "11 - 15", metric: "28 - 38" },
    life_span: "12 – 15 years",
  },
  {
    id: 197,
    image: "https://cdn2.thedogapi.com/images/rJFJVxc4m.jpg",
    name: "Poodle (Toy)",
    temperament: "no info",
    weight: { imperial: "6 - 9", metric: "3 - 4" },
    height: { imperial: "9 - 11", metric: "23 - 28" },
    life_span: "18 years",
  },
  {
    id: 201,
    image: "https://cdn2.thedogapi.com/images/HyJvcl9N7.jpg",
    name: "Pug",
    temperament:
      "Docile, Clever, Charming, Stubborn, Sociable, Playful, Quiet, Attentive",
    weight: { imperial: "14 - 18", metric: "6 - 8" },
    height: { imperial: "10 - 12", metric: "25 - 30" },
    life_span: "12 - 14 years",
  },
  {
    id: 204,
    image: "https://cdn2.thedogapi.com/images/ryPgVl5N7.jpg",
    name: "Puli",
    temperament: "Energetic, Agile, Loyal, Obedient, Intelligent, Faithful",
    weight: { imperial: "25 - 35", metric: "11 - 16" },
    height: { imperial: "16 - 17", metric: "41 - 43" },
    life_span: "12 - 16 Years years",
  },
  {
    id: 205,
    image: "https://cdn2.thedogapi.com/images/SyRe4xcN7.jpg",
    name: "Pumi",
    temperament: "Lively, Reserved, Intelligent, Active, Protective, Vocal",
    weight: { imperial: "18 - 33", metric: "8 - 15" },
    height: { imperial: "15 - 18.5", metric: "38 - 47" },
    life_span: "13 - 15 years",
  },
  {
    id: 207,
    image: "https://cdn2.thedogapi.com/images/HkXWNl9E7.jpg",
    name: "Rat Terrier",
    temperament:
      "Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving",
    weight: { imperial: "8 - 25", metric: "4 - 11" },
    height: { imperial: "10 - 13", metric: "25 - 33" },
    life_span: "12 - 18 years",
  },
  {
    id: 208,
    image: "https://cdn2.thedogapi.com/images/HJMzEl5N7.jpg",
    name: "Redbone Coonhound",
    temperament:
      "Affectionate, Energetic, Independent, Companionable, Familial, Unflappable",
    weight: { imperial: "45 - 80", metric: "20 - 36" },
    height: { imperial: "21 - 27", metric: "53 - 69" },
    life_span: "10 - 12 years",
  },
  {
    id: 209,
    image: "https://cdn2.thedogapi.com/images/By9zNgqE7.jpg",
    name: "Rhodesian Ridgeback",
    temperament:
      "Strong Willed, Mischievous, Loyal, Dignified, Sensitive, Intelligent",
    weight: { imperial: "75 - 80", metric: "34 - 36" },
    height: { imperial: "24 - 27", metric: "61 - 69" },
    life_span: "10 - 12 years",
  },
  {
    id: 210,
    image: "https://cdn2.thedogapi.com/images/r1xXEgcNX.jpg",
    name: "Rottweiler",
    temperament:
      "Steady, Good-natured, Fearless, Devoted, Alert, Obedient, Confident, Self-assured, Calm, Courageous",
    weight: { imperial: "75 - 110", metric: "34 - 50" },
    height: { imperial: "22 - 27", metric: "56 - 69" },
    life_span: "8 - 10 years",
  },
  {
    id: 211,
    image: "https://cdn2.thedogapi.com/images/HkP7Vxc4Q.jpg",
    name: "Russian Toy",
    temperament: "no info",
    weight: { imperial: "3 - 6", metric: "1 - 3" },
    height: { imperial: "7.5 - 10.5", metric: "19 - 27" },
    life_span: "10 - 12 years",
  },
  {
    id: 212,
    image: "https://cdn2.thedogapi.com/images/_Qf9nfRzL.png",
    name: "Saint Bernard",
    temperament: "Friendly, Lively, Gentle, Watchful, Calm",
    weight: { imperial: "130 - 180", metric: "59 - 82" },
    height: { imperial: "25.5 - 27.5", metric: "65 - 70" },
    life_span: "7 - 10 years",
  },
  {
    id: 213,
    image: "https://cdn2.thedogapi.com/images/fjFIuehNo.jpg",
    name: "Saluki",
    temperament: "Aloof, Reserved, Intelligent, Quiet",
    weight: { imperial: "35 - 65", metric: "16 - 29" },
    height: { imperial: "23 - 28", metric: "58 - 71" },
    life_span: "12 - 14 years",
  },
  {
    id: 214,
    image: "https://cdn2.thedogapi.com/images/S1T8Ee9Nm.jpg",
    name: "Samoyed",
    temperament: "Stubborn, Friendly, Sociable, Lively, Alert, Playful",
    weight: { imperial: "50 - 60", metric: "23 - 27" },
    height: { imperial: "19 - 23.5", metric: "48 - 60" },
    life_span: "12 - 14 years",
  },
  {
    id: 216,
    image: "https://cdn2.thedogapi.com/images/SyBvVgc47.jpg",
    name: "Schipperke",
    temperament: "Fearless, Agile, Curious, Independent, Confident, Faithful",
    weight: { imperial: "10 - 16", metric: "5 - 7" },
    height: { imperial: "10 - 13", metric: "25 - 33" },
    life_span: "13 - 15 years",
  },
  {
    id: 218,
    image: "https://cdn2.thedogapi.com/images/SkNjqx9NQ.jpg",
    name: "Scottish Deerhound",
    temperament: "Docile, Friendly, Dignified, Gentle",
    weight: { imperial: "70 - 130", metric: "32 - 59" },
    height: { imperial: "28 - 32", metric: "71 - 81" },
    life_span: "8 - 10 years",
  },
  {
    id: 219,
    image: "https://cdn2.thedogapi.com/images/Bklnce5NX.jpg",
    name: "Scottish Terrier",
    temperament: "Feisty, Alert, Independent, Playful, Quick, Self-assured",
    weight: { imperial: "18 - 22", metric: "8 - 10" },
    height: { imperial: "10", metric: "25" },
    life_span: "11 - 13 years",
  },
  {
    id: 221,
    image: "https://cdn2.thedogapi.com/images/rJa29l9E7.jpg",
    name: "Shetland Sheepdog",
    temperament:
      "Affectionate, Lively, Responsive, Alert, Loyal, Reserved, Playful, Gentle, Intelligent, Active, Trainable, Strong",
    weight: { imperial: "30", metric: "14" },
    height: { imperial: "13 - 16", metric: "33 - 41" },
    life_span: "12 - 14 years",
  },
  {
    id: 222,
    image: "https://cdn2.thedogapi.com/images/Zn3IjPX3f.jpg",
    name: "Shiba Inu",
    temperament: "Charming, Fearless, Keen, Alert, Confident, Faithful",
    weight: { imperial: "17 - 23", metric: "8 - 10" },
    height: { imperial: "13.5 - 16.5", metric: "34 - 42" },
    life_span: "12 - 16 years",
  },
  {
    id: 223,
    image: "https://cdn2.thedogapi.com/images/BkrJjgcV7.jpg",
    name: "Shih Tzu",
    temperament:
      "Clever, Spunky, Outgoing, Friendly, Affectionate, Lively, Alert, Loyal, Independent, Playful, Gentle, Intelligent, Happy, Active, Courageous",
    weight: { imperial: "9 - 16", metric: "4 - 7" },
    height: { imperial: "8 - 11", metric: "20 - 28" },
    life_span: "10 - 18 years",
  },
  {
    id: 225,
    image: "https://cdn2.thedogapi.com/images/SJJxjecEX.jpg",
    name: "Shiloh Shepherd",
    temperament: "Outgoing, Loyal, Companionable, Gentle, Loving, Trainable",
    weight: { imperial: "120 - 140", metric: "54 - 64" },
    height: { imperial: "26 - 30", metric: "66 - 76" },
    life_span: "9 – 14 years",
  },
  {
    id: 226,
    image: "https://cdn2.thedogapi.com/images/S17ZilqNm.jpg",
    name: "Siberian Husky",
    temperament: "Outgoing, Friendly, Alert, Gentle, Intelligent",
    weight: { imperial: "35 - 60", metric: "16 - 27" },
    height: { imperial: "20 - 23.5", metric: "51 - 60" },
    life_span: "12 years",
  },
  {
    id: 228,
    image: "https://cdn2.thedogapi.com/images/ByzGsl5Nm.jpg",
    name: "Silky Terrier",
    temperament: "Friendly, Responsive, Inquisitive, Alert, Quick, Joyful",
    weight: { imperial: "8 - 10", metric: "4 - 5" },
    height: { imperial: "9 - 10", metric: "23 - 25" },
    life_span: "12 - 15 years",
  },
  {
    id: 233,
    image: "https://cdn2.thedogapi.com/images/HJHmix5NQ.jpg",
    name: "Soft Coated Wheaten Terrier",
    temperament:
      "Affectionate, Spirited, Energetic, Playful, Intelligent, Faithful",
    weight: { imperial: "30 - 40", metric: "14 - 18" },
    height: { imperial: "16 - 18", metric: "41 - 46" },
    life_span: "12 - 15 years",
  },
  {
    id: 235,
    image: "https://cdn2.thedogapi.com/images/HJf4jl9VX.jpg",
    name: "Spanish Water Dog",
    temperament:
      "Trainable, Diligent, Affectionate, Loyal, Athletic, Intelligent",
    weight: { imperial: "30 - 50", metric: "14 - 23" },
    height: { imperial: "16 - 20", metric: "41 - 51" },
    life_span: "12 - 15 years",
  },
  {
    id: 236,
    image: "https://cdn2.thedogapi.com/images/rk5Eoe5Nm.jpg",
    name: "Spinone Italiano",
    temperament: "Docile, Friendly, Affectionate, Loyal, Patient, Gentle",
    weight: { imperial: "61 - 85", metric: "28 - 39" },
    height: { imperial: "22.5 - 27.5", metric: "57 - 70" },
    life_span: "10 - 12 years",
  },
  {
    id: 238,
    image: "https://cdn2.thedogapi.com/images/H1zSie9V7.jpg",
    name: "Staffordshire Bull Terrier",
    temperament:
      "Reliable, Fearless, Bold, Affectionate, Loyal, Intelligent, Courageous",
    weight: { imperial: "24 - 38", metric: "11 - 17" },
    height: { imperial: "14 - 16", metric: "36 - 41" },
    life_span: "12 - 14 years",
  },
  {
    id: 239,
    image: "https://cdn2.thedogapi.com/images/tmzeu6ID_.jpg",
    name: "Standard Schnauzer",
    temperament:
      "Trainable, Good-natured, Devoted, Lively, Playful, Intelligent",
    weight: { imperial: "30 - 50", metric: "14 - 23" },
    height: { imperial: "17.5 - 19.5", metric: "44 - 50" },
    life_span: "13 - 15 years",
  },
  {
    id: 242,
    image: "https://cdn2.thedogapi.com/images/HJ-Dix94Q.jpg",
    name: "Swedish Vallhund",
    temperament: "Fearless, Friendly, Energetic, Alert, Intelligent, Watchful",
    weight: { imperial: "20 - 30", metric: "9 - 14" },
    height: { imperial: "11.5 - 13.5", metric: "29 - 34" },
    life_span: "12 - 14 years",
  },
  {
    id: 243,
    image: "https://cdn2.thedogapi.com/images/zv89hR-O8.jpg",
    name: "Thai Ridgeback",
    temperament:
      "Protective, Loyal, Independent, Intelligent, Loving, Familial",
    weight: { imperial: "35 - 55", metric: "16 - 25" },
    height: { imperial: "20 - 24", metric: "51 - 61" },
    life_span: "10 - 12 years",
  },
  {
    id: 244,
    image: "https://cdn2.thedogapi.com/images/SkM9sec47.jpg",
    name: "Tibetan Mastiff",
    temperament:
      "Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective",
    weight: { imperial: "85 - 140", metric: "39 - 64" },
    height: { imperial: "24 - 26", metric: "61 - 66" },
    life_span: "10 - 14 years",
  },
  {
    id: 245,
    image: "https://cdn2.thedogapi.com/images/Hyjcol947.jpg",
    name: "Tibetan Spaniel",
    temperament:
      "Willful, Aloof, Assertive, Independent, Playful, Intelligent, Happy",
    weight: { imperial: "9 - 15", metric: "4 - 7" },
    height: { imperial: "10", metric: "25" },
    life_span: "12 - 15 years",
  },
  {
    id: 246,
    image: "https://cdn2.thedogapi.com/images/6f5n_42mB.jpg",
    name: "Tibetan Terrier",
    temperament:
      "Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive",
    weight: { imperial: "20 - 24", metric: "9 - 11" },
    height: { imperial: "14 - 17", metric: "36 - 43" },
    life_span: "12 - 15 years",
  },
  {
    id: 248,
    image: "https://cdn2.thedogapi.com/images/B17ase9V7.jpg",
    name: "Toy Fox Terrier",
    temperament: "Friendly, Spirited, Alert, Loyal, Playful, Intelligent",
    weight: { imperial: "4 - 9", metric: "2 - 4" },
    height: { imperial: "8 - 11", metric: "20 - 28" },
    life_span: "12 - 15 years",
  },
  {
    id: 250,
    image: "https://cdn2.thedogapi.com/images/SkRpsgc47.jpg",
    name: "Treeing Walker Coonhound",
    temperament:
      "Clever, Affectionate, Confident, Intelligent, Loving, Trainable",
    weight: { imperial: "45 - 80", metric: "20 - 36" },
    height: { imperial: "20 - 27", metric: "51 - 69" },
    life_span: "10 - 13 years",
  },
  {
    id: 251,
    image: "https://cdn2.thedogapi.com/images/r1o0jx9Em.jpg",
    name: "Vizsla",
    temperament: "Affectionate, Energetic, Loyal, Gentle, Quiet",
    weight: { imperial: "50 - 65", metric: "23 - 29" },
    height: { imperial: "21 - 24", metric: "53 - 61" },
    life_span: "10 - 14 years",
  },
  {
    id: 253,
    image: "https://cdn2.thedogapi.com/images/SyU12l9V7.jpg",
    name: "Weimaraner",
    temperament:
      "Steady, Aloof, Stubborn, Energetic, Alert, Intelligent, Powerful, Fast",
    weight: { imperial: "55 - 90", metric: "25 - 41" },
    height: { imperial: "23 - 27", metric: "58 - 69" },
    life_span: "12 - 15 years",
  },
  {
    id: 254,
    image: "https://cdn2.thedogapi.com/images/BJ1gnx5Vm.jpg",
    name: "Welsh Springer Spaniel",
    temperament: "Stubborn, Friendly, Affectionate, Loyal, Playful, Active",
    weight: { imperial: "35 - 55", metric: "16 - 25" },
    height: { imperial: "17 - 19", metric: "43 - 48" },
    life_span: "12 - 15 years",
  },
  {
    id: 256,
    image: "https://cdn2.thedogapi.com/images/Bkdx2g5Em.jpg",
    name: "West Highland White Terrier",
    temperament: "Hardy, Friendly, Alert, Independent, Gay, Active, Courageous",
    weight: { imperial: "15 - 22", metric: "7 - 10" },
    height: { imperial: "10 - 11", metric: "25 - 28" },
    life_span: "15 - 20 years",
  },
  {
    id: 257,
    image: "https://cdn2.thedogapi.com/images/Hyv-ne94m.jpg",
    name: "Whippet",
    temperament: "Friendly, Affectionate, Lively, Gentle, Intelligent, Quiet",
    weight: { imperial: "25 - 35", metric: "11 - 16" },
    height: { imperial: "18 - 22", metric: "46 - 56" },
    life_span: "12 - 15 years",
  },
  {
    id: 258,
    image: "https://cdn2.thedogapi.com/images/r14M3e9E7.jpg",
    name: "White Shepherd",
    temperament:
      "Self-confidence, Aloof, Fearless, Alert, Companionable, Eager",
    weight: { imperial: "60 - 85", metric: "27 - 39" },
    height: { imperial: "22 - 25", metric: "56 - 64" },
    life_span: "12 – 14 years",
  },
  {
    id: 259,
    image: "https://cdn2.thedogapi.com/images/SJ6f2g9EQ.jpg",
    name: "Wire Fox Terrier",
    temperament: "Fearless, Friendly, Bold, Keen, Alert, Quick",
    weight: { imperial: "15 - 19", metric: "7 - 9" },
    height: { imperial: "13 - 16", metric: "33 - 41" },
    life_span: "13 – 14 years",
  },
  {
    id: 260,
    image: "https://cdn2.thedogapi.com/images/Bkam2l9Vm.jpg",
    name: "Wirehaired Pointing Griffon",
    temperament: "Loyal, Gentle, Vigilant, Trainable, Proud",
    weight: { imperial: "45 - 70", metric: "20 - 32" },
    height: { imperial: "20 - 24", metric: "51 - 61" },
    life_span: "12 - 14 years",
  },
  {
    id: 261,
    image: "https://cdn2.thedogapi.com/images/r1I4hl5Em.jpg",
    name: "Wirehaired Vizsla",
    temperament: "no info",
    weight: { imperial: "45 - 65", metric: "20 - 29" },
    height: { imperial: "21.5 - 25", metric: "55 - 64" },
    life_span: "12 - 14 years",
  },
  {
    id: 262,
    image: "https://cdn2.thedogapi.com/images/HkNS3gqEm.jpg",
    name: "Xoloitzcuintli",
    temperament:
      "Cheerful, Alert, Companionable, Intelligent, Protective, Calm",
    weight: { imperial: "9 - 31", metric: "4 - 14" },
    height: { imperial: "10 - 23", metric: "25 - 58" },
    life_span: "12 - 14 years",
  },
  {
    id: 264,
    image: "https://cdn2.thedogapi.com/images/B12BnxcVQ.jpg",
    name: "Yorkshire Terrier",
    temperament: "Bold, Independent, Confident, Intelligent, Courageous",
    weight: { imperial: "4 - 7", metric: "2 - 3" },
    height: { imperial: "8 - 9", metric: "20 - 23" },
    life_span: "12 - 16 years",
  },
];
const temperaments = [
  { id: 1, name: "Stubborn" },
  { id: 2, name: " Curious" },
  { id: 3, name: " Playful" },
  { id: 4, name: " Adventurous" },
  { id: 5, name: " Active" },
  { id: 6, name: " Fun-loving" },
  { id: 7, name: "Aloof" },
  { id: 8, name: " Clownish" },
  { id: 9, name: " Dignified" },
  { id: 10, name: " Independent" },
  { id: 11, name: " Happy" },
  { id: 12, name: "Wild" },
  { id: 13, name: " Hardworking" },
  { id: 14, name: " Dutiful" },
  { id: 15, name: "Outgoing" },
  { id: 16, name: " Friendly" },
  { id: 17, name: " Alert" },
  { id: 18, name: " Confident" },
  { id: 19, name: " Intelligent" },
  { id: 20, name: " Courageous" },
  { id: 21, name: "Loyal" },
  { id: 22, name: " Brave" },
  { id: 23, name: "Docile" },
  { id: 24, name: " Responsive" },
  { id: 25, name: " Composed" },
  { id: 26, name: " Receptive" },
  { id: 27, name: " Faithful" },
  { id: 28, name: "Loving" },
  { id: 29, name: " Protective" },
  { id: 30, name: " Trainable" },
  { id: 31, name: " Responsible" },
  { id: 32, name: "Friendly" },
  { id: 33, name: " Energetic" },
  { id: 34, name: " Loyal" },
  { id: 35, name: " Gentle" },
  { id: 36, name: " Affectionate" },
  { id: 37, name: " Devoted" },
  { id: 38, name: " Assertive" },
  { id: 39, name: " Dominant" },
  { id: 40, name: "Strong Willed" },
  { id: 41, name: " Stubborn" },
  { id: 42, name: " Obedient" },
  { id: 43, name: " Reserved" },
  { id: 44, name: "Kind" },
  { id: 45, name: " Sweet-Tempered" },
  { id: 46, name: " Loving" },
  { id: 47, name: "Tenacious" },
  { id: 48, name: " Attentive" },
  { id: 49, name: "Steady" },
  { id: 50, name: " Bold" },
  { id: 51, name: " Proud" },
  { id: 52, name: "Reliable" },
  { id: 53, name: " Fearless" },
  { id: 54, name: " Lively" },
  { id: 55, name: "Cautious" },
  { id: 56, name: " Self-assured" },
  { id: 57, name: " Eager" },
  { id: 58, name: "Good-natured" },
  { id: 59, name: "Spirited" },
  { id: 60, name: " Companionable" },
  { id: 61, name: " Even Tempered" },
  { id: 62, name: " Rugged" },
  { id: 63, name: " Fierce" },
  { id: 64, name: " Refined" },
  { id: 65, name: "Obedient" },
  { id: 66, name: " Joyful" },
  { id: 67, name: "Affectionate" },
  { id: 68, name: " Agile" },
  { id: 69, name: "Amiable" },
  { id: 70, name: " Excitable" },
  { id: 71, name: " Determined" },
  { id: 72, name: "Self-confidence" },
  { id: 73, name: " Hardy" },
  { id: 74, name: "Fearless" },
  { id: 75, name: " Calm" },
  { id: 76, name: " Spirited" },
  { id: 77, name: " Good-tempered" },
  { id: 78, name: "Watchful" },
  { id: 79, name: " Hard-working" },
  { id: 80, name: "Energetic" },
  { id: 81, name: "Feisty" },
  { id: 82, name: " Cheerful" },
  { id: 83, name: " Sensitive" },
  { id: 84, name: "Easygoing" },
  { id: 85, name: " Adaptable" },
  { id: 86, name: " Trusting" },
  { id: 87, name: " Lovable" },
  { id: 88, name: " Territorial" },
  { id: 89, name: " Keen" },
  { id: 90, name: "Protective" },
  { id: 91, name: " Familial" },
  { id: 92, name: " Rational" },
  { id: 93, name: "Devoted" },
  { id: 94, name: " Bright" },
  { id: 95, name: "Agile" },
  { id: 96, name: " Quick" },
  { id: 97, name: "Trainable" },
  { id: 98, name: " Reliable" },
  { id: 99, name: " Powerful" },
  { id: 100, name: "Hardy" },
  { id: 101, name: " Gay" },
  { id: 102, name: " Stable" },
  { id: 103, name: " Quiet" },
  { id: 104, name: " Inquisitive" },
  { id: 105, name: "Alert" },
  { id: 106, name: " Strong" },
  { id: 107, name: " Sociable" },
  { id: 108, name: " Patient" },
  { id: 109, name: "Suspicious" },
  { id: 110, name: " Great-hearted" },
  { id: 111, name: " Merry" },
  { id: 112, name: " Vocal" },
  { id: 113, name: " Tolerant" },
  { id: 114, name: " Mischievous" },
  { id: 115, name: " People-Oriented" },
  { id: 116, name: " Bossy" },
  { id: 117, name: " Cunning" },
  { id: 118, name: " Watchful" },
  { id: 119, name: " Cautious" },
  { id: 120, name: "Playful" },
  { id: 121, name: " Easygoing" },
  { id: 122, name: " Athletic" },
  { id: 123, name: "Boisterous" },
  { id: 124, name: " Cooperative" },
  { id: 125, name: " Kind" },
  { id: 126, name: "Intelligent" },
  { id: 127, name: " Trustworthy" },
  { id: 128, name: "Self-important" },
  { id: 129, name: "Respectful" },
  { id: 130, name: "Sweet-Tempered" },
  { id: 131, name: " Thoughtful" },
  { id: 132, name: " Generous" },
  { id: 133, name: "Mischievous" },
  { id: 134, name: " Cat-like" },
  { id: 135, name: " Sturdy" },
  { id: 136, name: "Benevolent" },
  { id: 137, name: "Clownish" },
  { id: 138, name: " Outgoing" },
  { id: 139, name: "Keen" },
  { id: 140, name: "Clever" },
  { id: 141, name: " Docile" },
  { id: 142, name: "Sociable" },
  { id: 143, name: " Bubbly" },
  { id: 144, name: "Opinionated" },
  { id: 145, name: " Good-natured" },
  { id: 146, name: " Aggressive" },
  { id: 147, name: " Suspicious" },
  { id: 148, name: "Bold" },
  { id: 149, name: "Extroverted" },
  { id: 150, name: "no info" },
  { id: 151, name: "no info" },
  { id: 152, name: " Clever" },
  { id: 153, name: " Charming" },
  { id: 154, name: "Lively" },
  { id: 155, name: " Unflappable" },
  { id: 156, name: "Charming" },
  { id: 157, name: " Spunky" },
  { id: 158, name: " Diligent" },
  { id: 159, name: " Tenacious" },
  { id: 160, name: " Aloof" },
  { id: 161, name: "Willful" },
  { id: 162, name: " Amiable" },
  { id: 163, name: " Fast" },
  { id: 164, name: " Vigilant" },
  { id: 165, name: "Cheerful" },
];
/**
 * GET product list.
 *
 * @return product list | empty.
 */
/* const getInfoDB = async () => {
  //const data=await getInfoAPI();
  const data = await Dog.findAll({
    include: {
      model: Temperament,
      attributes: ["name"], //atributos que quiero traer del modelo Temperament, el id lo trae automatico
      through: {
        attributes: [], //traer mediante los atributos del modelo
      },
    },
  });
  return data;
}; */
/* const getAllDogs = async () => {
  const [api, db] = [infoapi, await getInfoDB()];
  //console.log(db);
  return [...api, ...db];
}; */
 router.get("/db", async (req, res) => {
  try {
    const datadb = await getInfoDB();
    res.json(datadb);
  } catch (error) {
    console.error(error);
  }
}); 
router.post("/dogs", async (req, res) => {
  try {
    const {
      name,
      temperament,
      min_height,
      max_height,
      min_weight,
      max_weight,
      image,
      life_span,
    } = req.body;
    const height = `${min_height} - ${max_height}`;
    const weight = `${min_weight} - ${max_weight}`;

    const dog = await Dog.create({
      name,
      temperament,
      height: { metric: height },
      weight: { metric: weight },
      life_span,
      image,
    });
    ////console.log(temperament);
    const [tempd, created] = await Temperament.findOrCreate({
      where: { name: temperament },
    });
    /*  let temperamentDB = await Temperament.findAll({
      where: { name: "Active"},
    }); */
    dog.addTemperament(tempd);
    /* console.log(dog)
    res.json(dog); */
    res.send("created");
  } catch (error) {
    console.error(error);
  }
});

router.get("/dogs", async (req, res) => {
  try {

//    const infototal = await getAllDogs();
const infototal=infoapi;
    const { name } = req.query;
    const { id } = req.query;
    if (name) {
      const filtered = infototal.filter((e) =>
        e.name.toLowerCase().includes(name.toLowerCase())
      );
      filtered.length
        ? res.status(200).send(filtered)
        : res.status(200).send("not has been founded");
    } else if (id) {
      const filtroid = infototal.filter((e) => e.id == id);
      filtroid.length
        ? res.status(200).send(filtroid)
        : res.status(200).send("not has been founded");
    } else {
      infototal.length ? res.json(infototal) : res.send("not has been founded");
    }
  } catch (error) {
    console.error(error);
  }
});
router.get("/dogs/:id", async (req, res) => {
  const { id } = req.params;
  //const dog = await getAllDogs();
  const dog = infoapi;
  const dogfound = dog.filter((e) => e.id == id);
  dogfound
    ? res.status(200).json(dogfound)
    : res.send("not has been founded in the database");
});
router.get("/temperaments", async (req, res) => {
  try {
    res.json(temperaments);
  } catch (error) {
    console.error(error);
    return res.status(500).send("Server error");
  }
});
router.get("/apiexterna", async (req, res) => {
  try {
    res.json(infoapi);
  } catch (error) {
    console.error(error);
    return res.status(500).send("Server error");
  }
});
router.get("/h", async (req, res) => {
  try {
    res.send("hola");
  } catch (error) {
    console.error(error);
    return res.status(500).send("Server error");
  }
});

module.exports = router;
